name: blnk_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_native_splash: 2.4.1
  shared_preferences: 2.3.3
  provider: 6.1.5
  flutter_svg: 2.1.0
  bot_toast: 4.1.3
  package_info_plus: 8.3.0
  google_fonts: 6.2.1
  easy_stepper: 0.8.5+1
  http: 1.4.0
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
